"""
Formatador HTML para saída de dados
"""

from discord_lookup.formatters.base import BaseFormatter


class HTMLFormatter(BaseFormatter):
    """Formata a saída como HTML"""
    
    @staticmethod
    def format(user) -> str:
        """
        Converte um único usuário para HTML
        
        Args:
            user: Objeto DiscordUser
            
        Returns:
            str: HTML formatado
        """
        data = BaseFormatter.get_user_data(user)
        
        return f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Discord User: {data['username']}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 40px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 800px;
            margin: 0 auto;
            background-color: white;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }}
        .header {{
            background-color: #5865F2;
            color: white;
            padding: 20px;
            text-align: center;
        }}
        .content {{
            padding: 20px;
        }}
        table {{
            width: 100%;
            table-layout: fixed;
            border-collapse: collapse;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            white-space: nowrap;
        }}
        th {{
            background-color: #f2f2f2;
        }}
        .avatar {{
            border-radius: 50%;
            width: 100px;
            height: 100px;
        }}
        .avatar-cell {{
            text-align: center;
        }}
        .badge {{
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: bold;
        }}
        .badge-bot {{
            background-color: #ff6b6b;
            color: white;
        }}
        .badge-user {{
            background-color: #51b46d;
            color: white;
        }}
        .footer {{
            background-color: #f2f2f2;
            padding: 15px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }}
        .banner {{
            max-width: 100%;
            height: auto;
            border-radius: 8px;  /* ou 0 para sem borda */
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Discord User Information</h1>
        </div>
        <div class="content">
            <table>
                <tr><th>Field</th><th>Value</th></tr>
                <tr><th>ID</th><td>{data['id']}</td></tr>
                <tr><th>Username</th><td>{data['username']}</td></tr>
                <tr><th>Discriminator</th><td>#{data['discriminator']}</td></tr>
                <tr><th>Global Name</th><td>{data['global_name'] or 'N/A'}</td></tr>
                <tr class="avatar-cell">
                    <th>Avatar</th>
                    <td><img src="{data['avatar_url']}" alt="Avatar" class="avatar"></td>
                </tr>
                <tr><th>Banner</th>
                    <td>{f'<img src="{data["banner_url"]}" class="banner" width="400">' if data['banner_url'] else 'No banner'}</td></tr>
                <tr><th>Bot</th><td><span class="badge {'badge-bot' if data['is_bot'] else 'badge-user'}">{'Yes' if data['is_bot'] else 'No'}</span></td></tr>
                <tr><th>Created At</th><td>{data['created_at']}</td></tr>
                <tr><th>Public Flags</th><td>{data['public_flags']}</td></tr>
            </table>
        </div>
        <div class="footer">
            Generated by Discord Lookup Tool
        </div>
    </div>
</body>
</html>"""
    
    @staticmethod
    def save_to_file(user, filename: str) -> None:
        """
        Salva um único usuário em arquivo HTML
        
        Args:
            user: Objeto DiscordUser
            filename: Nome do arquivo para salvar
        """
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(HTMLFormatter.format(user))
    
    @staticmethod
    def format_batch(results: list) -> str:
        """
        Formata resultados de batch como HTML
        
        Args:
            results: Lista de resultados do batch processing
            
        Returns:
            str: HTML com tabela de resultados
        """
        success_count = sum(1 for r in results if r['success'])
        error_count = len(results) - success_count
        
        # Construir linhas da tabela
        rows = ""
        for result in results:
            if result['success']:
                data = result['data']
                banner_html = f'<img src="{data["banner_url"]}" width="100" class="banner" loading="lazy">' if data.get('banner_url') else ''
                rows += f"""
                <tr style="background-color: #e8f5e9;">
                    <td>{result['user_id']}</td>
                    <td><span class="badge badge-user">SUCCESS</span></td>
                    <td>{data.get('username', '')}</td>
                    <td>{data.get('discriminator', '')}</td>
                    <td>{data.get('global_name') or ''}</td>
                    <td><img src="{data.get('avatar_url', '')}" width="50" class="avatar"></td>
                    <td>{banner_html}</td>
                    <td>{data.get('created_at', '')}</td>
                    <td style="text-align: center;">{data.get('public_flags', 0)}</td>
                    <td>{'Yes' if data.get('is_bot') else 'No'}</td>
                    <td></td>
                </tr>"""
            else:
                rows += f"""
                <tr style="background-color: #ffebee;">
                    <td>{result['user_id']}</td>
                    <td><span class="badge badge-bot">ERROR</span></td>
                    <td colspan="11">{result.get('error', 'Unknown error')}</td>
                </tr>"""
        
        return f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Discord Batch Results</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 40px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1400px;
            margin: 0 auto;
            background-color: white;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }}
        .header {{
            background-color: #5865F2;
            color: white;
            padding: 20px;
            text-align: center;
        }}
        .stats {{
            display: flex;
            justify-content: space-around;
            padding: 20px;
            background-color: #f8f9fa;
        }}
        .stat-box {{
            text-align: center;
        }}
        .stat-number {{
            font-size: 24px;
            font-weight: bold;
        }}
        .stat-label {{
            color: #666;
        }}
        .content {{
            padding: 20px;
            overflow-x: auto;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
            white-space: nowrap;
        }}
        th {{
            background-color: #5865F2;
            color: white;
        }}
        .avatar {{
            border-radius: 50%;
        }}
        .badge {{
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: bold;
        }}
        .badge-bot {{
            background-color: #ff6b6b;
            color: white;
        }}
        .badge-user {{
            background-color: #51b46d;
            color: white;
        }}
        .footer {{
            background-color: #f2f2f2;
            padding: 15px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Discord Batch Results</h1>
        </div>
        <div class="stats">
            <div class="stat-box">
                <div class="stat-number">{len(results)}</div>
                <div class="stat-label">Total</div>
            </div>
            <div class="stat-box">
                <div class="stat-number" style="color: #51b46d;">{success_count}</div>
                <div class="stat-label">Success</div>
            </div>
            <div class="stat-box">
                <div class="stat-number" style="color: #ff6b6b;">{error_count}</div>
                <div class="stat-label">Error</div>
            </div>
        </div>
        <div class="content">
            <table>
                <thead>
                    <tr>
                        <th>User ID</th>
                        <th>Status</th>
                        <th>Username</th>
                        <th>Discriminator</th>
                        <th>Global Name</th>
                        <th>Avatar</th>
                        <th>Banner URL</th>
                        <th>Created At</th>
                        <th>Public Flags</th>
                        <th>Bot</th>
                        <th>Error</th>
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </div>
        <div class="footer">
            Generated by Discord Lookup Tool
        </div>
    </div>
</body>
</html>"""
    
    @staticmethod
    def save_batch_to_file(results: list, filename: str) -> None:
        """
        Salva resultados de batch em arquivo HTML
        
        Args:
            results: Lista de resultados do batch processing
            filename: Nome do arquivo para salvar
        """
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(HTMLFormatter.format_batch(results))